spring.application.name=parqueadero
spring.datasource.url=jdbc:h2:mem:parqueaderodb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Esto asegura que las tablas se creen de cero y se ejecute el import.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

springdoc.swagger-ui.path=/swagger-ui.html
server.port=8082